import { Heart } from 'lucide-react'
import { useEffect, useState } from 'react'
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from '../../../components/ui/avatar'
import { Button } from '../../../components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../../../components/ui/dialog'
import { useInfiniteScrollDialog } from '../../../hooks/effectsSkeletons'
import type { Persons } from '../../../types'
import { filter } from '../../../utils/functions'
import { Input } from '../../ui/input'
import { FollowerSkeleton } from './Skeleton'

// Dados fictícios — substitua depois pela lista real

let seguidores: Persons[] = [
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
  { id: 1, nome: 'Julia Ferreira', avatar: '' },
  { id: 2, nome: 'Matheus Costa', avatar: '' },
  { id: 3, nome: 'Camila Rocha', avatar: '' },
  { id: 4, nome: 'Enzo Martins', avatar: '' },
  { id: 5, nome: 'Isabela Lima', avatar: '' },
  { id: 6, nome: 'Thiago Almeida', avatar: '' },
  { id: 7, nome: 'Larissa Mendes', avatar: '' },
  { id: 8, nome: 'Gustavo Silva', avatar: '' },
  { id: 9, nome: 'Sofia Ribeiro', avatar: '' },
  { id: 10, nome: 'Renato Oliveira', avatar: '' },
]

export function FollowersDialog() {
  const [visibleCount, setVisibleCount] = useState(10)
  const [loadedCount, setLoadedCount] = useState(10)
  const [open, setOpen] = useState(false)
  const [search, setSearch] = useState<string>('')
  const [seguidoresFiltrados, setSeguidoresFiltrados] = useState(seguidores)
  const [empty, setEmpty] = useState(false)

  const hasMore = visibleCount < seguidoresFiltrados.length

  const { scrollContainerRef, loadMoreRef } = useInfiniteScrollDialog({
    enabled: open,
    hasMore,
    openDelayMs: 350,
    rootMargin: '300px',
    onLoadMore: () => {
      const next = Math.min(visibleCount + 10, seguidoresFiltrados.length)
      setVisibleCount(next)
      setTimeout(() => {
        setLoadedCount(next)
      }, 1000)
    },
  })

  useEffect(() => {
    if (open) {
      setSearch('')
      setVisibleCount(10)
      setLoadedCount(10)
      filter(search, seguidores, setSeguidoresFiltrados, setEmpty)
    }
  }, [open])
  useEffect(() => {
    if (open) {
      filter(search, seguidores, setSeguidoresFiltrados, setEmpty)
      setLoadedCount(10)
      setLoadedCount(10)
    }
  }, [search])
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <button className="flex cursor-pointer items-center gap-1.5 rounded-lg px-3 py-2 transition-colors hover:bg-muted">
          <span className="text-xl font-bold text-foreground">1.2k</span>
          <span className="flex items-center gap-1 text-sm text-muted-foreground">
            <Heart className="h-4 w-4 text-red-600" />
            seguidores
          </span>
        </button>
      </DialogTrigger>

      <DialogContent className="max-w-md rounded-2xl border bg-background/95 p-6 shadow-xl backdrop-blur-sm">
        <DialogHeader>
          <DialogTitle className="text-center text-2xl font-semibold text-foreground">
            Seguidores de Carlos Almeida
          </DialogTitle>
          <p className="mt-2 text-center text-muted-foreground">
            {seguidores.length} pessoas seguindo
          </p>
          <div>
            <Input
              type="text"
              placeholder="Buscar seguidores"
              className="mt-4"
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
        </DialogHeader>

        <div
          ref={scrollContainerRef}
          className="mt-6 h-[500px] space-y-3 overflow-y-auto"
        >
          {seguidoresFiltrados.slice(0, visibleCount).map((seguidor, index) => {
            const isLoaded = index < loadedCount

            return (
              <div key={seguidor.id + '-' + index}>
                {isLoaded ? (
                  <div className="flex items-center gap-4 rounded-xl border bg-card p-4 transition-colors hover:bg-muted/50">
                    <Avatar className="h-12 w-12">
                      <AvatarImage src={seguidor.avatar} alt={seguidor.nome} />
                      <AvatarFallback className="bg-linear-purple font-medium text-white">
                        {seguidor.nome
                          .split(' ')
                          .map((n) => n[0])
                          .join('')
                          .toUpperCase()}
                      </AvatarFallback>
                    </Avatar>

                    <div className="flex-1">
                      <p className="font-medium text-foreground">
                        {seguidor.nome}
                      </p>
                    </div>

                    <Button size="sm" className="bg-linear-purple rounded-full">
                      Ver perfil
                    </Button>
                  </div>
                ) : (
                  <FollowerSkeleton />
                )}
              </div>
            )
          })}
          {empty && (
            <p className="mb-4 flex items-center justify-center text-muted-foreground">
              Nenhum usuário encontrado
            </p>
          )}

          {hasMore && <div ref={loadMoreRef} className="col-span-2 h-[1px]" />}
        </div>
      </DialogContent>
    </Dialog>
  )
}
